### ISSUE TITLE
加入血月时改变玩家的队伍颜色

### ISSUE THREAD

**Issue by LeonXu98** [NyaaCat/bloodmoon#10]
使用记分板的队伍功能，让玩家和怪物不是同种队伍颜色，减少由于玩家使用产生发光状态效果的道具后造成的误伤。当玩家退出血月后重置玩家的队伍颜色为默认，使用指令返回血月后恢复血月时的队伍颜色。

**Comment by phoenixlzx** [comment]
经测试，该选项设置无效。

scoreboard 命令可生效，但血月开始后被重置为白色且无法再设置。

**Comment by phoenixlzx** [comment]
于是确定问题是 IM 在一直刷新玩家的 scoreboard 导致。

目前暂时禁用了 IM 的 scoreboard

提议，可以[修改 IM 的 scoreboard 行为而非 BM](https://github.com/NyaaCat/InfernalMobs/blob/master/src/main/java/com/jacob_vejvoda/infernal_mobs/GUI.java#L30)。

**Comment by cyilin** [comment]
为了显示不同怪物信息，scoreboard没法共用，只能考虑在IM更新scoreboard时排除血月玩家了。
