### ISSUE TITLE
关于mostkill、mostassist与mostnormalkill加权计算的提议

### ISSUE THREAD

**Issue by assange0** [NyaaCat/bloodmoon#3]
现阶段单纯依靠统计击杀数目来赋予奖励，但是由于黑化等级不同，难度不同，如果玩家倾向于击杀稍低等级的黑化或者普通怪物，相同时间内取得的数目就会偏大，这样似乎不太合理。
　　因此建议在此基础上为不同难度的怪物设置权值，以最后得出的加权数来判定mostkill、mostassist与mostnormalkill。

**Comment by phoenixlzx** [comment]
我觉得可以，有实现逻辑的 PR 么

**Comment by assange0** [comment]
然而并木有，我还没学过JAVA 😂
