### ISSUE TITLE
改进血月的奖励方案

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/bloodmoon#4]
Reference: #3 

目前的想法：

* 更改 `reward.yml` 为权重计分

```
normal:
  kill: 3
infernal:
  kill:
    '1': 5
    '2': 6
    '3': 7
    '4': 8
    '5': 9
    '6': 10
    '7': 11
    '8': 12
```

`reward.normal.kill` 为每个普通怪物击杀的计分，`reward.infernal.kill.[level]` 为每个黑化怪击杀的计分。注意这里的 `level` 是黑化的等级，不是攻击波数。

* 助攻的判定

一只黑化被击杀后，最终击杀的玩家获得对应等级全部的计分，所有对该黑化造成伤害的玩家（为避免重复计分，最终击杀的玩家除外）获得分数为 `击杀分数 * (输出伤害/助攻伤害总血量)`

例：一只血量为 230 的 Lv 8 黑化被 4 名玩家击杀的数据如下：

玩家 A 击杀 / 玩家 B 造成 30 点伤害 / 玩家 C 造成 100 点伤害 / 玩家 D 造成 50 点伤害

则分数判定为：A 获得 12 分 / B 获得 `12 * (30 / (30 + 100 + 50)) = 2` 分 / C 获得 `12 * (100 / (30 + 100 + 50)) = 6.67` 分 / D 获得 `12 * (50 / (30 + 100 + 50)) = 3.33` 分

* 摸鱼的判定

如果一个参与的玩家：

1. 杀死了队友
2. 被队友杀死
3. 两波以上的攻击里没有一次怪物击杀记录

满足以上任意条件则判定该玩家在摸鱼。目前暂时不设置摸鱼的额外惩罚。

* Top player 的判定

1. 最多黑化击杀玩家 1 名
2. 最多普通怪击杀玩家 1 名
3. 最多助攻玩家 1 名

如果有 2 名或以上同样数量的玩家，取总分较高的玩家。

总分最高的玩家获得 MVP。也就是该规则下，总是会有一名玩家获得 MVP。

* 奖励的设定

只有战斗胜利才会获得奖励。如果战斗失败则不发放任何奖励。

金钱奖励：每位玩家将按分数获得金钱奖励。

奖励箱：保存于单独的配置文件 `kit.yml`，被判定为摸鱼的玩家将不会得到该类型的奖励。

奖励箱的种类，除 `MOSTKILL`，`MOSTASSIST`，`MOSTNORMALKILL` 和 `MVP`，另外新增一个种类 `TEAM`。

举例来说，`MOSTKILL`，`MOSTASSIST`，`MOSTNORMALKILL` 和 `MVP` 奖励给获得对应奖项的玩家，而 `TEAM` 则奖励给全体非摸鱼的玩家。奖励规则是所有坚持到最后的玩家将获得该 kit 中随机的一个物品（一个槽）。

**Comment by RecursiveG** [comment]
新`reward.yml`格式
``` yaml
normal_kill_point: {number}
infernal_kill_point:
  '1': {number}
  '2': {number}
  '3': {number}
kits:
  "kit1":
    "MOSTKILL":
      - {item1}
      - {item2}
      - {item3}
    "MOSTASSIST":
      - {item1}
      - {item2}
      - {item3}
    "MOSTNORMALKILL":
      - {item1}
      - {item2}
      - {item3}
    "MVP":
      - {item1}
      - {item2}
      - {item3}
    "TEAM":
      - {item1}
      - {item2}
      - {item3}

**Comment by phoenixlzx** [comment]
友伤的判定更新，出现友军击杀的时候击杀玩家和被杀玩家都会被扣掉一定的分数，这个分数可以在配置文件中定义。

如果分数为 0 或负值则判定为摸鱼，不记入奖励。
